### ISSUE TITLE
Fix: show image in Article component

### ISSUE THREAD

**Issue by vicistomin** [inoagents/react-project-kitchen-frontend#46]
Image should be between these tags:
https://github.com/inoagents/react-project-kitchen-frontend/blob/c0a2142e279caf40d3ec2eeacb7c9766235f22b3/src/components/Article/Article.js#L57-L58

Screenshot from Figma:
![image](https://user-images.githubusercontent.com/20445297/125422554-0c8d84a2-8e35-4957-9275-e605698f494d.png)

**Comment by z0rig** [comment]
Не понимаю что в alt описание писать, в объекте, описывающем статью ничего подходящего как будто нет.
Или мы по-умолчанию предполагаем, что title статьи должен описывать картинку?

**Comment by vicistomin** [comment]
> Не понимаю что в alt описание писать, в объекте, описывающем статью ничего подходящего как будто нет.
> Или мы по-умолчанию предполагаем, что title статьи должен описывать картинку?

Я думаю, что в качестве title можно использовать article.title, а в качестве alt — поле article.description (это краткое описание статьи).
А так — да, отдельных полей ввода для описания/названия картинки сейчас нет.
